version: '2.3'
services:
  python:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      args:
        - UID=${USERID}
    volumes:
      - .:/usr/src
      - /mnt/D/Data/chibiv2:/usr/src/data
    working_dir: /usr/src
    shm_size: '8gb'
